// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLibrary.Data;

#nullable disable

namespace MyLibrary.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyLibrary.Models.LivrosModel", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Autor")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NomeDoLivro")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Paginas")
                    .HasColumnType("int");

                b.Property<DateTime>("UltimaAtualizacao")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("Livros", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}